### ISSUE TITLE
Migration from helm2 to helm3

### ISSUE THREAD

**Issue by xtremerui** [concourse/hush-house#126]
Since right now we have 'CI' that deployed with helm3 already. We could start migrate other deployments from helm2 to helm3 following https://github.com/helm/helm-2to3

After all is done the makefiles and readme should be updated accordingly.

**Comment by chenbh** [comment]
Worked on this a bit today, changes are on `issue/126` branch. Following in footstep of CI, it'll be templated by helm3 and deployed by kapp.

It's mostly functional, but is blocked on https://github.com/concourse/concourse-chart/pull/176 if we want to keep the `SYS_PTRACE` capability

**Comment by xtremerui** [comment]
in our toolchain this upgrade is finished
