### ISSUE TITLE
hh: move external url from `concourse-ci.org` to `pivotal.io` and update certificates

### ISSUE THREAD

**Issue by cirocosta** [concourse/hush-house#25]
Hey,

With `hush-house` graduating to "being a thing" for Pivotal folks, we're going to update the external URL to `hush-house.pivotal.io`.

Once we get the domain mapped to this address, we can then:

- [x] update the external url that we set for the Chart https://github.com/concourse/hush-house/blob/d2fefbe7aaef68f8aff4670be84adf98c5f26dc6/deployments/with-creds/hush-house/values.yaml#L71
- [x] update the certificates in our hidden `.values.yaml` file.
- [x] update URL in [Datadog SLI variable](https://p.datadoghq.com/sb/bb663c3fb-a77113d61e5ee7378c2cca01876febeb)
- [x] Update URL in README

Thanks!

**Comment by YoussB** [comment]
The current cert that we have is signed for https://house-house.pivotal.io/ Whoops 😅.
we were able to successfully deploy to the house-house domain as a test.
 waiting for the new cert and the `dns A record` to move to hush-house.pivotal.io

**Comment by pivotal-bin-ju** [comment]
**Dev Note**
- externalUrl has been updated as `https://hush-house.pivotal.io`
- `.values.yaml` is created and acquired the secrets from lastpass.
- server cert and key have been updated according to the new domain name, in that case `hush-house.pivotal.io` is ready to serve.

==========
ToDo:
- Doc update for the new domain name`https://hush-house.pivotal.io`.
- OAuth2 with github integration. Currently the auth still with the old domain name `https://hush-house.concourse-ci.org`.

**Comment by YoussB** [comment]
ToDo: we'll need to recreate/reset the `deploy` pipeline after #30 is merged.
