### ISSUE TITLE
Configuration endpoint for Credhub secrets provider

### ISSUE THREAD

**Issue by aegershman** [concourse/hush-house#32]
For credentials management, I'd like a configuration endpoint for credhub.

Although there doesn't appear to be a helmchart to deploy credhub on Kubernetes, I'd like to configure our Concourse helm chart to leverage our existing credhub deployed via BOSH running within the same VPC.

[Currently there are `values.yml` endpoints for vault, awsSsm, and awsSecretsManager](https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L305); could one be opened up for Credhub as well?

**Comment by cirocosta** [comment]
Hey @aegershman,

Good point! It's indeed missing 😬 

Would you mind creating an issue / PR under `helm/charts` though?

Here we're only keeping track of what's needed for our internal environment where we set up Concourse on k8s.

Thanks!

**Comment by aegershman** [comment]
Apologies I wasn't sure of the best place to log issues specific to the helm chart-- the [`concourse/charts`](https://github.com/concourse/charts) fork doesn't allow for logging issues-- so moving forward, logging issues/PRs directly to `helm/charts` is the best way to solicit feedback/make PRs? https://github.com/helm/charts/issues Just making sure. Thanks!

**Comment by cirocosta** [comment]
Oh, no problem! We're happy to see people contributing to our repos 😁  😁  

Creating issues/PR against `helm/charts` directly is what we're expecting as the `concourse/charts` is mostly an internal fork that we use to either submit our own PRs or play with custom features before we make PRs.

Thanks!!
