### ISSUE TITLE
metrics: alert based on SLIs

### ISSUE THREAD

**Issue by cirocosta** [concourse/hush-house#39]
Hey,

At the moment, we have our SLIs (see [Datadog SLI Dashboard][sli-dashboard]) being displayed in a monitor in the office, but this does not necessarily mean that the operators (Test Pilot Pair) end up acting on problems that happen there, as the pair would need to keep looking at it.

![sli-hurt](https://user-images.githubusercontent.com/3574444/56815553-a4314000-680f-11e9-8622-ad709cd10087.png)

By tying those SLIs with PagerDuty, we're then able to treat degradations in those numbers as triggers for action.

To better reflect the fact that an alert is generated, we should also update the way that the colors are set there (such that it's immediate for someone to see that there's an active incident).

In terms of "which thresholds to use", let's start with an SLO of daily 95 (which means  1h12m of downtime), and adjust that accordingly.

**Acceptance criteria**

- [x] With a daily SLI being hurt, a page is generated to PagerDuty
- [x] Have Datadog colors representing our objectives.

Thanks!

[sli-dashboard]: https://p.datadoghq.com/sb/bb663c3fb-a77113d61e5ee7378c2cca01876febeb

**Comment by scottietremendous** [comment]
We should have follow up issues to continually raise the SLOs.

**Comment by cirocosta** [comment]
@pivotal-bin-ju  🙌 

![Screen Shot 2019-04-29 at 4 50 53 PM](https://user-images.githubusercontent.com/3574444/56926155-018ef080-6a9f-11e9-880d-da4256180708.png)
![Screen Shot 2019-04-29 at 4 51 07 PM](https://user-images.githubusercontent.com/3574444/56926156-018ef080-6a9f-11e9-8f17-14b4efb7c3d4.png)

**Comment by cirocosta** [comment]
Whoops, it turns out that we were performing the evaluations in a `1m` interval (which is pretty much a 99.93% daily).

Now we're also including error budgets that tell us how much time we have left to explore aiming at that 99% monthly:

<img width="734" alt="Screen Shot 2019-05-01 at 10 00 52 AM" src="https://user-images.githubusercontent.com/3574444/57020704-25b21500-6bf8-11e9-94a2-add93833738d.png">
