### ISSUE TITLE
Move metrics Github to the Concourse org

### ISSUE THREAD

**Issue by YoussB** [concourse/hush-house#55]
[updated by @cirocosta ]

When logging into `metrics-hush-house.concourse-ci.org` making use of the GitHub login, the user is prompted to sign into an application that is currently owned by @cirocosta's GitHub account.

What we should have, instead, is an application under the Concourse org (we might have a bot account or something that manages `metrics.concourse-ci.org` which we could leverage).

**Comment by taylorsilva** [comment]
Site is now using a Concourse org Oauth app
