### ISSUE TITLE
Update the worker config to `hosts` for `concourse.worker.tsa.host`

### ISSUE THREAD

**Issue by zoetian** [concourse/hush-house#60]
After the changes for https://github.com/helm/charts/pull/15220, we need to update the hush-house as well to use `concourse.worker.tsa.hosts`.

The file can be found here:
https://github.com/concourse/hush-house/blob/eb4dbf1cdd79774fc23136e504dc6319946d8ddc/deployments/with-creds/worker/values.yaml#L51

**Comment by cirocosta** [comment]
done 23e838ad767629d631030379d12e53e00bb1791d
