### ISSUE TITLE
'view build history' SLI

### ISSUE THREAD

**Issue by jamieklassen** [concourse/hush-house#86]
Since this afternoon, [this SLI](https://app.datadoghq.com/monitors/9682021) has been dipping. I haven't been able to confidently correlate this against any deploys or workloads on hush-house itself -- maybe it's just incentive to prioritize improving performance on the `ListAllBuilds` endpoint.

**Comment by xtremerui** [comment]
https://github.com/concourse/hush-house/pull/88 should help improve hush-house SLI

**Comment by xtremerui** [comment]
SLI is moved to wavefront and alerts are sending to concourse-interrupt. It has being worked as expected.
