### ISSUE TITLE
data migration for vault

### ISSUE THREAD

**Issue by pivotal-bin-ju** [concourse/hush-house#91]
To switch to a new `vault` with a different backend rather than `file`, a migration program is needed.

This program should:
- with less dependencies. vault might work on `bosh`, and might work in a container as well.
- not a `bash` script. For our case, `kubectl exec` can only have a `sh` interface with the current `vault` 
- import and output should be two separated procedure due to the source and destination network interconnectivity. A file / some files  can be the media for import / export purpose

**Comment by cirocosta** [comment]
doone 😁  thanks!!
